# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ShibbityShwab.LightSpeed
PackageVersion: 1.6.14
InstallerType: msi
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ShibbityShwab/lightspeed/releases/download/v1.6.14/lightspeed-gui-x86_64-pc-windows-msvc.msi
  InstallerSha256: 2A3DD57E6734A53F3B36896048982AB533756801BD2F2FAC4D01B0787B08CC5A
  InstallerSwitches:
    Silent: /qn
    SilentWithProgress: /qn
    Custom: /norestart
ManifestType: installer
ManifestVersion: 1.6.0
